openapi: 3.0.3
info:
  title: Shawty URL Shortener API
  version: 1.0.0
  description: |
    Shawty is a modern URL shortening service with user authentication, protected APIs, and user-specific link management.

servers:
  - url: http://localhost:3000
    description: Local development server

tags:
  - name: Auth
    description: User registration and login
  - name: URL
    description: URL shortening and redirection
  - name: Links
    description: User-specific link management

paths:
  /api/auth/register:
    post:
      tags: [Auth]
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, email, password]
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '201':
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Invalid input or user already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/auth/login:
    post:
      tags: [Auth]
      summary: Login and receive a JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/shorten:
    post:
      tags: [URL]
      summary: Shorten a long URL
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [longUrl]
              properties:
                longUrl:
                  type: string
                  format: uri
      responses:
        '201':
          description: URL shortened successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UrlResponse'
        '400':
          description: Invalid URL or missing input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/links/my-links:
    get:
      tags: [Links]
      summary: Get all links created by the authenticated user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of user links
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  count:
                    type: integer
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Url'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /{code}:
    get:
      tags: [URL]
      summary: Redirect to the original URL
      parameters:
        - in: path
          name: code
          required: true
          schema:
            type: string
          description: Short URL code
      responses:
        '301':
          description: Redirect to the original URL
        '404':
          description: No URL found for this code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        email:
          type: string
          format: email

    UserResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        data:
          $ref: '#/components/schemas/User'

    LoginResponse:
      type: object
      properties:
        success:
          type: boolean
        token:
          type: string
        user:
          $ref: '#/components/schemas/User'

    Url:
      type: object
      properties:
        _id:
          type: string
        urlCode:
          type: string
        longUrl:
          type: string
          format: uri
        shortUrl:
          type: string
          format: uri
        date:
          type: string
          format: date-time
        clicks:
          type: integer
        user:
          type: string

    UrlResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        data:
          $ref: '#/components/schemas/Url'

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string